$(documen).ready(function(){
    $(".main").click(function(){
        $("#design").toggle();
        $("#space").toggle();
    });
    $(".mai").click(function(){
        $("#development").toggle();
        $("#road").toggle();
    });
    $(".kim").click(function(){
        $("#product").toggle();
        $("#craft").toggle();
    });
});
